version: '3.8'

services:
  frcallbacks:
    image: postgres:15-alpine # Versão estável e leve
    container_name: frcallbacks
    restart: always
    environment:
      POSTGRES_USER: frcallbacks
      POSTGRES_PASSWORD: frcallbacks123
      POSTGRES_DB: frcallbacks
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Opcional: Script para inicializar o banco automaticamente
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - pg-network

  # Opcional: Interface gráfica para gerenciar o banco pelo navegador
  #pgadmin:
  #  image: dpage/pgadmin4
  #  container_name: pgadmin_gui
  #  restart: always
  #  environment:
  #    PGADMIN_DEFAULT_EMAIL: admin@admin.com
  #    PGADMIN_DEFAULT_PASSWORD: admin
  #  ports:
  #    - "8081:80"
  #  depends_on:
  #    - db
  #  networks:
  #    - pg-network

volumes:
  postgres_data:

networks:
  pg-network:
    driver: bridge